name: Setup
description: Setup Node.js and install dependencies (Yarn Berry)

inputs:
  working-directory:
    description: Folder to run install
    required: false
    default: .
  node-version-file:
    description: Path to .nvmrc or .node-version
    required: false
    default: .nvmrc
  registry-url:
    description: Optional npm registry URL (e.g. https://registry.npmjs.org)
    required: false
    default: ''
  scope:
    description: Optional npm scope for auth (e.g. @smiles)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        check-latest: false

    - name: Enable Corepack & pin Yarn
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        corepack enable
        # Garante Yarn da repo config (se existir .yarnrc.yml)
        corepack prepare yarn@stable --activate || true
        echo "yarn_version=$(yarn --version)" >> "$GITHUB_OUTPUT"
      id: yarn

    - name: Configure npm registry
      if: ${{ inputs.registry-url != '' }}
      shell: bash
      run: |
        set -euo pipefail
        npm config set registry "${{ inputs.registry-url }}"
        if [ -n "${{ inputs.scope }}" ]; then
          npm config set ${{ inputs.scope }}:registry "${{ inputs.registry-url }}"
        fi

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          packages/*/node_modules
          .yarn/install-state.gz
        key: |
          ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-yarn-${{ steps.yarn.outputs.yarn_version }}-lock-${{ hashFiles('**/yarn.lock') }}-pkgjson-${{ hashFiles('**/package.json', '!**/node_modules/**') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        YARN_ENABLE_GLOBAL_CACHE: "0"
      run: |
        set -euo pipefail
        yarn install --immutable --check-cache
